In [1]:
import numpy as np


In [6]:
# Matrix Multipication 
arr1 = np.array([[1,2],[3,4]])  
arr2 = np.array([[5,6],[7,8]])  
print("Result of Matrix Multiplication of :\n", arr1 , " \nand \n" , arr2)
print("is\n",np.dot(arr1,arr2)) 

Result of Matrix Multiplication of :
 [[1 2]
 [3 4]]  
and 
 [[5 6]
 [7 8]]
is
 [[19 22]
 [43 50]]


In [8]:
 #inverse function
a = np.array([[1,2],[5,6]])  
inverse =np.linalg.inv(a)
print("The inverse of \n" , a , "is \n" , inverse)

The inverse of 
 [[1 2]
 [5 6]] is 
 [[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [10]:
# Rank of Matrix
arr = np.array([[1,2],[3,4]])  
print("The rank of matrix\n", arr, " is " ,np.linalg.matrix_rank(arr)) 

The rank of matrix
 [[1 2]
 [3 4]]  is  2


In [11]:
# Determinant of Matrix
arr = np.array([[1,2],[3,4]])  
print("The Determinant of matrix\n", arr, " is \n" ,np.linalg.det(arr))

The Determinant of matrix
 [[1 2]
 [3 4]]  is 
 -2.0000000000000004


In [12]:
# Max and Min
arr= np.array([[1,23,78],[98,60,75],[79,25,48]]) 
print("The array is ", arr)
print("The minimum element is ", np.amin(arr))
print("The maximum element is ", np.amax(arr))

The array is  [[ 1 23 78]
 [98 60 75]
 [79 25 48]]
The minimum element is  1
The maximum element is  98


In [22]:

arr = np.array([7,8,8,9])
weights_arr = np.array([7,1,2,3])
print("The array is", arr)
print("Mean = ",np.mean(arr))
print("Median = ", np.median(arr))
print("Standard Deviation = ", np.std(arr))
print("Variance = ", np.var(arr))
print("Weighted Avg = ", np.average(arr, weights=weights_arr))

The array is [7 8 8 9]
Mean =  8.0
Median =  8.0
Standard Deviation =  0.7071067811865476
Variance =  0.5
Weighted Avg =  7.6923076923076925


In [25]:
# Generating Data using Probability Distribution
normal_data =  np.random.normal(0, 1, 25)
uniform_data =  np.random.uniform(0, 1, 25)
poisson_data = np.random.poisson(5, 25)
print("\n25 Random Values with 0 mean & 1 SD using Normal Distribution\n" , normal_data)
print("\n25 Random Values with 0 mean & 1 SD using Uniform Distribution\n" , uniform_data)
print("\n25 Random Values with 5 lambda using Poisson Distribution\n" , poisson_data)


25 Random Values with 0 mean & 1 SD using Normal Distribution
 [-0.66057122  0.53054862  1.96472672  0.46290802  1.19212348 -1.41499092
  1.35032703 -1.05662584  0.22231894  0.39985031 -0.30282779 -0.13957877
  1.53195952  0.39466097  1.07737196  1.21347492  0.32139958  0.08859802
  0.6039657  -2.19717965  0.56038763 -0.37517437 -1.09362262 -0.7474733
  1.22529016]

25 Random Values with 0 mean & 1 SD using Uniform Distribution
 [0.10107893 0.23427583 0.18439587 0.73686375 0.02056479 0.55616804
 0.15975267 0.79897315 0.93758198 0.59147908 0.98853197 0.65966962
 0.54627446 0.69032387 0.22085544 0.86474429 0.24608632 0.86562671
 0.87024572 0.63643413 0.18808217 0.88667353 0.37091676 0.75296458
 0.92481869]

25 Random Values with 5 lambda using Poisson Distribution
 [ 3  3  2 10  6  7  4  2  4  5  5  4  7  6  8  6  3  5  4  8  7  3  7  4
  5]
