In [1]:
import numpy as np

In [4]:
# Broadcasting with a scalar
arr = np.arange(5)
print("Original Array:",arr)
print("Broadcasting with scalar 2",arr * 2)

Original Array: [0 1 2 3 4]
Broadcasting with scalar 2 [0 2 4 6 8]


In [6]:
# Demeaning the Column
matrix_ = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
col_means = matrix_.mean(axis=0)
new_matrix = matrix_ - col_means
print("Original array:\n", matrix_)
print("Column means:", col_means)
print("Demeaned array:\n", new_matrix)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column means: [4. 5. 6.]
Demeaned array:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [8]:
# Demeaning the Row
# We reshape here because the trailing shape doesn't match with starting of other so we reshape to introduce 1 in it
matrix_ = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])
col_means = matrix_.mean(axis=1)
new_matrix = matrix_ - col_means.reshape((4,1))
print("Original array:\n", matrix_)
print("Row means:", col_means)
print("Demeaned array:\n", new_matrix)

Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Row means: [ 2.  5.  8. 11.]
Demeaned array:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [11]:
# Broadcasting over other axis 3-D
arr = np.random.randn(2, 3, 4)
depth_means = arr.mean(axis=2) # shape 2,3
demeaned_arr = arr - depth_means[:,:,np.newaxis]# New axis introduces another col
print("Original array:\n", arr)
print("Depth means:", depth_means)
print("Demeaned array:\n", demeaned_arr)

Original array:
 [[[-3.01548539 -0.12070765 -0.31408136 -0.24941057]
  [ 0.28712683  2.32384606  0.00716717  0.28020328]
  [-0.83202237  1.05989365 -1.10272188  0.96123805]]

 [[ 0.5276671  -0.18737577 -0.57934591 -0.42637053]
  [ 0.53137521  1.19550329 -1.65181049  0.11374416]
  [-0.25133581 -0.16367747 -0.9515684   0.4675587 ]]]
Depth means: [[-0.92492124  0.72458584  0.02159686]
 [-0.16635628  0.04720304 -0.22475575]]
Demeaned array:
 [[[-2.09056415  0.80421359  0.61083989  0.67551067]
  [-0.437459    1.59926023 -0.71741867 -0.44438256]
  [-0.85361923  1.03829679 -1.12431874  0.93964119]]

 [[ 0.69402338 -0.02101949 -0.41298963 -0.26001426]
  [ 0.48417217  1.14830024 -1.69901353  0.06654112]
  [-0.02658007  0.06107828 -0.72681266  0.69231445]]]


In [19]:
# Setting Values Using Broadcasting
arr = np.zeros((3,3))
row = np.array([4,5,6])
print("The original array is ", arr)
arr[:] = row
print("Updated Array after setting values ", arr)

The original array is  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Updated Array after setting values  [[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]
